nome = input('Digite o nome completo: ')
maiusculo = nome.upper()
print('Em letras maiúsculas:  {}' .format(maiusculo))
minusculo = nome.lower()
print('Em letras minúsculas:  {}' .format(minusculo))
espaco = len(nome.replace(' ', ''))
print('O nome completo {} possui {} letras'.format(nome, espaco) )
primeiro = len(nome.split()[0])
print('O primeiro nome {} tem {} letras' .format(nome.split()[0], primeiro))
