n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('É um número? ', n.isnumeric())
print('É alfanumerico? ', n.isalnum())
print('É alfabetico? ', n.isalpha())
print('É letra minuscula? ', n.islower())
print('É letra maiuscula? ',n.isupper())
print('É numero decimal? ',n.isdecimal())
print('É printavel? ',n.isprintable())
print('Só tem espaço?', n.isspace())
